Repository ingresse/design-systems-android, pull requests merged in 2019-12, with the labels that each got.

#31 Release/0.3.5
  design/build.gradle
  design/src/main/java/com/ingresse/design/helper/ColorHelper.kt
  design/src/main/java/com/ingresse/design/ui/button/ButtonEnums.kt
  design/src/main/java/com/ingresse/design/ui/button/DSButton.kt
  design/src/main/res/values/attrs.xml
  design/src/main/res/values/components.xml
  design/src/main/res/values/dimens.xml
  design/src/main/res/values/text_styles.xml
Labels: mobile

#33 Release/0.4.0
  .gitignore
  design/build.gradle
  design/src/main/java/com/ingresse/design/ui/button/DSButton.kt
  design/src/main/java/com/ingresse/design/ui/editText/DSEditText.kt
  design/src/main/res/layout/ds_edit_text.xml
  design/src/main/res/values/attrs.xml
  design/src/main/res/values/components.xml
Labels: feature, mobile

#32 Change DSButton pattern
  design/src/main/java/com/ingresse/design/ui/button/DSButton.kt
  design/src/main/res/values/components.xml
Labels: bravo, feature, mobile, tested, to deploy
